config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from config.api import api

# Personalize the Django admin header
admin.site.site_header = "Administration d’Open Collectivités"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    url(r"^favicon\.ico$", RedirectView.as_view(url="/static/favicon.ico")),
    path("api/", api.urls),
    path("cms/", include(wagtailadmin_urls)),
    path("wd_documents/", include(wagtaildocs_urls)),
    path("", include("core.urls")),
    path("", include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.error404"
handler500 = "core.views.error500"

core/urls.py
from django.urls import path, re_path
from . import views

app_name = "core"
urlpatterns = [
    path(
        "commune/<slug:slug>/",
        views.page_commune_detail,
        name="page_commune_detail",
    ),
    path(
        "epci/<slug:slug>/",
        views.page_epci_detail,
        name="page_epci_detail",
    ),
    path(
        "departement/<slug:slug>/",
        views.page_departement_detail,
        name="page_departement_detail",
    ),
    path(
        "departement/<slug:slug>/liste-communes/",
        views.page_departement_liste_communes,
        name="page_departement_liste_communes",
    ),
    path(
        "departement/<slug:slug>/liste-epcis/",
        views.page_departement_liste_epcis,
        name="page_departement_liste_epcis",
    ),
    path(
        "region/<slug:slug>/",
        views.page_region_detail,
        name="page_region_detail",
    ),
    path(
        "region/<slug:slug>/liste-communes/",
        views.page_region_liste_communes,
        name="page_region_liste_communes",
    ),
    path(
        "region/<slug:slug>/liste-epcis/",
        views.page_region_liste_epcis,
        name="page_region_liste_epcis",
    ),
    path(
        "region/<slug:slug>/liste-departements/",
        views.page_region_liste_departements,
        name="page_region_liste_departements",
    ),
    re_path(
        r"^compare\/commune\/(?P<slug1>[-\w]+)\/(?P<slug2>[-\w]+)\/?(?P<slug3>[-\w]+)?\/?(?P<slug4>[-\w]+)?\/?",
        views.page_commune_compare,
        name="page_commune_compare",
    ),
    path(
        "export/commune/<slug:slug>",
        views.csv_commune_export,
        name="csv_commune_export",
    ),
    re_path(
        r"^compare_export\/commune\/(?P<slug1>[-\w]+)\/(?P<slug2>[-\w]+)\/?(?P<slug3>[-\w]+)?\/?(?P<slug4>[-\w]+)?\/?",
        views.csv_compare_communes_from_list,
        name="csv_compare_communes_from_list",
    ),
    path(
        "compare_export/departement/membres/<slug:slug>",
        views.csv_departement_compare_communes,
        name="csv_departement_compare_communes",
    ),
    path(
        "compare_export/epci/membres/<slug:slug>",
        views.csv_epci_compare_communes,
        name="csv_epci_compare_communes",
    ),
    re_path(
        r"^compare\/.*",
        views.page_not_yet,
        name="page_place_compare",
    ),
    path("publications/", views.page_publications, name="page_publications"),
    path("tests/", views.page_tests, name="page_tests"),
    path("plan/", views.page_sitemap, name="page_sitemap"),
    path("test_404/", views.error404, {"exception": Exception()}, name="page_test_404"),
    path("test_500/", views.error500, {"exception": Exception()}, name="page_test_500"),
    path("test_50x/", views.error50x, {"exception": Exception()}, name="page_test_50x"),
]

opencollectivites/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r"^favicon\.ico$", RedirectView.as_view(url="/static/favicon.ico")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/france/", include("francesubdivisions.urls")),
    path("api/aspic/", include("aspic.urls")),
    path("", include("core.urls")),
]

core/views/base.py
from django.shortcuts import render
from django.views.decorators.http import require_safe
from core.models import Scope, Source, Topic
from core.services.utils import init_payload
from francedata.models import Region


@require_safe
def error404(request, exception):
    payload = init_payload("Erreur")
    payload["exception"] = exception
    return render(request, "core/404.html", payload, status=404)


@require_safe
def error500(request, *args, **argv):
    payload = init_payload("Erreur serveur")
    return render(request, "core/500.html", payload, status=500)


@require_safe
def error50x(request, *args, **argv):
    payload = init_payload("Erreur serveur")
    return render(request, "core/50x.html", payload, status=503)


@require_safe
def page_not_yet(request, **kwargs):
    payload = init_payload("Page en construction")
    return render(request, "core/page_not_yet.html", payload)


@require_safe
def page_sitemap(request):
    payload = init_payload("Plan du site")

    regions = Region.objects.order_by("name")
    regions_data = []
    for r in regions:
        regions_data.append(
            {"name": r.name, "slug": r.slug, "counts": r.subdivisions_count()}
        )

    filter_data = {}
    filter_data["topic"] = Topic.objects.order_by("name")
    filter_data["scope"] = Scope.objects.order_by("name")
    filter_data["source"] = Source.objects.order_by("title")
    payload["filter_data"] = filter_data

    payload["regions_data"] = regions_data

    return render(request, "core/sitemap.html", payload)


@require_safe
def page_tests(request):
    payload = init_payload("Tests")
    payload["breadcrumb_with_link"] = {
        "links": [{"url": "test-url", "title": "Test title"}],
        "current": "Test page",
    }
    payload["context"]["hide_brand"] = False
    return render(request, "core/tests.html", payload)

core/views/communes.py
from collectivity_pages.services.utils import get_messages_for_collectivity
from core.services.publications import list_publications_for_collectivity
from django.urls.base import reverse
from core.services.utils import init_payload
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_safe
from francedata.models import Commune

from collectivity_pages.services.communes import commune_data, communes_compare

from dsfr.utils import generate_summary_items


@require_safe
def page_commune_detail(request, slug):
    commune = get_object_or_404(Commune, slug=slug)

    payload = init_payload(f"Données locales commune : {commune.name}")
    payload["slug"] = slug
    payload["siren"] = commune.siren
    payload["commune_name"] = commune.name
    payload["data"] = commune_data(commune)
    payload["page_data"] = {"type": "commune", "slug": slug}
    payload["data"]["tables_header"] = ["Intitulé", "Donnée"]
    payload["data"]["table_header_zonage"] = ["Intitulé", "Statut"]
    payload["data"]["table_header_interco"] = ["Type", "Nom", "Sigle type"]

    payload["page_menu"] = {
        "title": "Sommaire",
        "items": generate_summary_items(
            [
                "Données de contexte",
                "Intercommunalités et zonage",
                "Ressources financières et fiscales",
                "Comparaison avec d’autres communes",
                "Études, statistiques et outils",
            ]
        ),
        "extra_classes": "fr-sidemenu--sticky-full-height fr-sidemenu--right",
    }

    payload["messages"] = get_messages_for_collectivity(
        collectivity_type="COMM", collectivity_slug=slug
    )

    payload["publications"] = list_publications_for_collectivity(
        collectivity_type="commune", collectivity_slug=commune.slug
    )

    payload["context"]["hide_brand"] = False
    return render(request, "core/commune_detail.html", payload)


@require_safe
def page_commune_compare(request, slug1, slug2, slug3=0, slug4=0):
    slugs = [slug1, slug2]
    communes = []
    slugs_dict = {"slug1": slug1, "slug2": slug2}

    """
    Storing all supplementary slugs in slug2 because the reverse() function is not able to 
    figure out the optional slashes.
    """
    if slug3:
        slugs.append(slug3)
        slugs_dict["slug2"] = f"{slugs_dict['slug2']}/{slug3}"
    if slug4:
        slugs.append(slug4)
        slugs_dict["slug2"] = f"{slugs_dict['slug2']}/{slug4}"

    for s in slugs:
        commune = get_object_or_404(Commune, slug=s)
        communes.append(commune)

    payload = init_payload("Comparaison de communes")
    payload["data"] = {}
    payload["data"]["tables"] = communes_compare(communes)
    payload["data"]["tables_header"] = ["Intitulé"] + payload["data"]["tables"][
        "places_names"
    ]

    payload["data"]["export_link"] = reverse(
        "core:csv_compare_communes_from_list", kwargs=slugs_dict
    )

    return render(request, "core/commune_compare.html", payload)

core/views/csv_exports.py
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_safe

from collectivity_pages.services.communes import (
    compare_communes_for_export,
)

from francedata.models import Departement, Commune, Epci


###############
# CSV exports #
###############
@require_safe
def csv_commune_export(request, slug):
    commune = Commune.objects.filter(slug=slug)
    # Commune.objects.filter is used instead of get_object_or_404 because
    # compare_communes_for_export expects a QuerySet
    filename = f"export-commune-{slug}"
    response = compare_communes_for_export(commune, filename)
    return response


@require_safe
def csv_compare_communes_from_list(request, slug1, slug2, slug3=0, slug4=0):
    slugs = [slug1, slug2]
    if slug3:
        slugs.append(slug3)
    if slug4:
        slugs.append(slug4)

    communes = Commune.objects.filter(slug__in=slugs)
    filename = f"comparaisons-communes-{'-'.join(slugs)}"

    response = compare_communes_for_export(communes, filename)
    return response


@require_safe
def csv_epci_compare_communes(request, slug):
    epci = get_object_or_404(Epci, slug=slug)
    filename = f"comparaisons-communes-{slug}"
    response = compare_communes_for_export(epci.commune_set.all(), filename)
    return response


@require_safe
def csv_departement_compare_communes(request, slug):
    departement = get_object_or_404(Departement, slug=slug)
    filename = f"comparaisons-communes-{slug}"
    response = compare_communes_for_export(departement.commune_set.all(), filename)
    return response

core/views/departements.py
from collectivity_pages.services.departements import departement_data
from collectivity_pages.services.utils import get_messages_for_collectivity
from core.services.publications import list_publications_for_collectivity
from core.services.utils import init_payload
from django.urls.base import reverse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_safe
from dsfr.utils import generate_summary_items
from francedata.models import Departement


@require_safe
def page_departement_detail(request, slug):
    departement = get_object_or_404(Departement, slug=slug)

    payload = init_payload(f"Données locales département : {departement.name}")
    payload["slug"] = slug
    payload["siren"] = departement.siren
    payload["data"] = departement_data(departement)
    payload["data"]["tables_header"] = ["Intitulé", "Donnée"]
    payload["page_menu"] = {
        "title": "Sommaire",
        "items": generate_summary_items(
            [
                "Données de contexte",
                "Ressources financières et fiscales",
                "Périmètre",
                "Études, statistiques et outils"
            ]
        ),
        "extra_classes": "fr-sidemenu--sticky-full-height fr-sidemenu--right",
    }

    payload["messages"] = get_messages_for_collectivity(
        collectivity_type="DEPT", collectivity_slug=slug
    )

    payload["publications"] = list_publications_for_collectivity(
        collectivity_type="departement", collectivity_slug=departement.slug
    )

    return render(request, "core/departement_detail.html", payload)


@require_safe
def page_departement_liste_communes(request, slug):
    departement = get_object_or_404(Departement, slug=slug)
    max_year = max(departement.commune_set.values_list("years", flat=True))
    communes = departement.commune_set.filter(years=max_year).order_by("name")
    payload = init_payload(
        f"Liste des { communes.count() } communes du département {departement.name}",
        links=[
            {
                "title": f"Fiche département : {departement.name}",
                "url": reverse(
                    "core:page_departement_detail", kwargs={"slug": departement.slug}
                ),
            }
        ],
    )
    payload["list"] = communes
    payload["entry_link"] = {
        "title": "Fiche commune",
        "view": "core:page_commune_detail",
    }
    return render(request, "core/place_list_direct_subdivisions.html", payload)


@require_safe
def page_departement_liste_epcis(request, slug):
    departement = get_object_or_404(Departement, slug=slug)
    max_year = max(departement.list_epcis().values_list("years", flat=True))
    epcis = departement.list_epcis().filter(years=max_year).order_by("slug")

    payload = init_payload(
        f"Liste des { len(epcis) } EPCI du département {departement.name}",
        links=[
            {
                "title": f"Fiche département : {departement.name}",
                "url": reverse(
                    "core:page_departement_detail", kwargs={"slug": departement.slug}
                ),
            }
        ],
    )
    payload["list"] = epcis
    payload["entry_link"] = {
        "title": "Fiche EPCI",
        "view": "core:page_epci_detail",
    }
    return render(request, "core/place_list_direct_subdivisions.html", payload)

core/views/epcis.py
from collectivity_pages.services.utils import get_messages_for_collectivity
from core.services.utils import init_payload
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_safe
from dsfr.utils import generate_summary_items
from francedata.models import Epci

from collectivity_pages.services.epcis import epci_data

from core.services.publications import (
    list_documents,
    documents_to_cards,
    list_publications_for_collectivity,
)


@require_safe
def page_epci_detail(request, slug):
    epci = get_object_or_404(Epci, slug=slug)

    payload = init_payload(f"Données locales intercommunalité : {epci.name}")
    payload["slug"] = slug
    payload["siren"] = epci.siren
    payload["epci_name"] = epci.name
    payload["data"] = epci_data(epci.siren)
    payload["data"]["tables_header"] = ["Intitulé", "Donnée"]

    payload["page_menu"] = {
        "title": "Sommaire",
        "items": generate_summary_items(
            [
                "Données socio-économiques",
                "Coordonnées du siège",
                "Périmètre & compétences",
                "Ressources financières et fiscales",
                "Études, statistiques et outils",
            ]
        ),
        "extra_classes": "fr-sidemenu--sticky-full-height fr-sidemenu--right",
    }

    tools, total_count = list_documents(document_type=3, publication_page=4, limit=10)
    payload["tools_list"] = documents_to_cards(tools)

    payload["messages"] = get_messages_for_collectivity(
        collectivity_type="EPCI", collectivity_slug=epci.slug
    )

    payload["publications"] = list_publications_for_collectivity(
        collectivity_type="epci", collectivity_slug=epci.slug
    )

    return render(request, "core/epci_detail.html", payload)

core/views/publications.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.conf import settings
from django.views.decorators.http import require_GET, require_safe

from core.services.utils import init_payload
from core.services.publications import (
    list_documents,
    documents_to_cards,
    publication_filters,
)


@require_safe
def page_publications(request):
    payload = init_payload("Études, statistiques et outils locaux")

    documents, total_count = list_documents(
        topic=request.GET.get("topic"),
        scope=request.GET.get("scope"),
        document_type=request.GET.get("document_type"),
        publication_page=request.GET.get("publication_page"),
        source_org=request.GET.get("source_org"),
        year=request.GET.get("year"),
        commune=request.GET.get("commune"),
        epci=request.GET.get("epci"),
        departement=request.GET.get("departement"),
        region=request.GET.get("region"),
        before=request.GET.get("before"),
        after=request.GET.get("after"),
    )

    cards = documents_to_cards(documents)

    paginated_docs = Paginator(cards, settings.PUBLICATIONS_PER_PAGE)

    data = {}
    data["total"] = paginated_docs.count
    data["cards_page"] = paginated_docs.get_page(request.GET.get("page"))

    payload["data"] = data

    payload["filters"] = publication_filters(request)

    return render(request, "core/publications.html", payload)

core/templates/core/blocks/collectivity_publications.html
{% if publications.instance.cards or publications.level.cards %}
  <section class="fr-mt-4w">
    <h2 id="etudes-statistiques-et-outils">Études, statistiques et outils</h2>
    {% if publications.instance.cards %}
      <div class="fr-mb-6w"">
        <div class="oc-heading-with-sidelink">
          <h3>{{ publications.instance.title }}</h3>
          {% if publications.instance.see_all %}
          <a
            class="fr-link fr-fi-arrow-right-line fr-link--icon-right"
            target="_self"
            href="{% url 'core:page_publications' %}?{{ publications.collectivity_type }}={{ publications.instance.slug }}"
            >Voir tout
          </a>
          {% endif %}
        </div>

        {% include "core/blocks/publications_list.html" with data=publications.instance.cards width_class="fr-col-md-4" %}
      </div>
    {% endif %}

    {% if publications.level.cards %}
    
      <div class="fr-mt-4w fr-mb-6w">
        <div class="oc-heading-with-sidelink">
          <h3>{{ publications.level.title }}</h3>
          {% if publications.level.see_all %}
          <a
            class="fr-link fr-fi-arrow-right-line fr-link--icon-right"
            target="_self"
            href="{% url 'core:page_publications' %}?publication_page={{ publications.level.publication_page_id }}"
            >Voir tout
          </a>
          {% endif %}
        </div>
        {% include "core/blocks/publications_list.html" with data=publications.level.cards width_class="fr-col-md-4" %}
      </div>
    {% endif %}
  </section>
{% endif %}

core/templates/core/blocks/compare_selector.html
<div id="vue-app" class="comparison-selector fr-bg--alt">
  {% verbatim %}
  <form @submit.prevent="loadResultPageCompare">
    <div class="fr-select-group">
    <label for="oc-compare-selector" class="fr-label">
      Sélectionnez jusqu'à trois collectivités :
    </label>
    <vue-multiselect
      v-model="places"
      id="oc-compare-selector"
      :options="options"
      track-by="value"
      label="text"
      :multiple="true"
      :max="3"
      :internal-search="false"
      :close-on-select="false"
      :loading="isLoading"
      :preserve-search="true"
      placeholder="Taper les premières lettres de la collectivité recherchée"
      @search-change="searchCollectivities"
      :options-limit="300"
      :limit="3"
      :limit-text="limitText"
      :show-labels="false"
    >
      <span slot="noOptions">Taper les premières lettres de la collectivité recherchée</span>
      <span slot="noResult" v-if="query.length < 3">Taper au moins trois caractères</span>
      <span slot="noResult" v-else>Aucun résultat trouvé, merci de vérifier votre saisie</span>
      <span slot="maxElements">Limite de sélection atteinte</span>
    </vue-multiselect>
    </div>
    <button type="submit" class="fr-btn fr-fi-checkbox-line fr-btn--icon-right" :isDisabled="!(places && places.length)">
      Comparer
    </button>
  </form>
  {% endverbatim %}
</div>

core/templates/core/blocks/footer.html
{% extends "dsfr/footer.html" %}
{% load wagtailcore_tags %}


{% block footer_links %}
<li class="fr-footer__bottom-item">
    <a class="fr-footer__bottom-link" href="{% url 'core:page_sitemap' %}">Plan du site</a>
</li>
<li class="fr-footer__bottom-item">
    <a class="fr-footer__bottom-link" href="{% slugurl 'accessibilite' %}">Accessibilité: {{ SITE_CONFIG.get_accessibility_status_display|default:'non' }} conforme</a>
</li>
<li class="fr-footer__bottom-item">
    <a class="fr-footer__bottom-link" href="{% slugurl 'mentions-legales' %}">Mentions légales</a>
</li>
<li class="fr-footer__bottom-item">
    <a class="fr-footer__bottom-link" href="{% slugurl 'mentions-legales' %}#donnees-personnelles">Données personnelles</a>
</li>
<li class="fr-footer__bottom-item">
    <a class="fr-footer__bottom-link" href="{% slugurl 'mentions-legales' %}#gestion-des-cookies">Gestion des cookies</a>
</li>
<li class="fr-footer__bottom-item">
    <a class="fr-footer__bottom-link" href="{% slugurl 'contact' %}">Contact</a>
</li>
<li class="fr-footer__bottom-item">
    <a class="fr-footer__bottom-link" href="{% slugurl 'faq' %}">FAQ</a>
</li>
<li class="fr-footer__bottom-item">
  <button type="button" class="fr-footer__bottom-link fr-fi-theme-fill fr-link--icon-left" aria-controls="fr-theme-modal" data-fr-opened="false">Paramètres d’affichage</button>
</li>
{% endblock %}

core/templates/core/blocks/footer_categories.html
{% load dsfr_tags %}
<div class="fr-container-fluid oc-bg--alt fr-pt-4w fr-pb-6w">
  <div id="categories-jumbotron" class="fr-container">
    <h2>
      Toutes les études, statistiques et outils par thématique
    </h2>
    <div id="home-categories" class="fr-grid-row fr-grid-row--gutters oc-svg-icons">
      {% for topic in context_topics %}
        <div class="fr-col-12 fr-col-md-2">
        {% dsfr_tile topic %}
        </div>
      {% endfor %}
    </div>
  </div>
</div>

core/templates/core/blocks/header.html
{% extends "dsfr/header.html" %}
{% load wagtailcore_tags %}
{% block brand %}
  {% if hide_brand is not True %}
    <a href="/" title="Accueil — {{ SITE_CONFIG.site_title }}">
      <p class="fr-logo">république<br>française</p>
    </a>
  {% else %}
    <a href="/" title="Accueil — {{ SITE_CONFIG.site_title }}">
      <p class="fr-logo"></p>
    </a>
  {% endif %}
{% endblock %}

{% block header_tools %}
<li>
  <button type="button" class="fr-link fr-fi-theme-fill fr-link--icon-left" aria-controls="fr-theme-modal" data-fr-opened="false">Paramètres d'affichage</button>
</li>
{% endblock%}

<!-- Leave both blocks below empty if the main menu is not used --> 
{% block burger_menu %}
{% endblock %}

{% block main_menu %}
    <div class="fr-header__menu fr-modal" id="fr-menu-modal" aria-labelledby="fr-btn-menu-modal">
      <div class="fr-container">
        <button type="button" class="fr-link--close fr-link" aria-controls="fr-menu-modal">Fermer</button>
        <div class="fr-header__menu-links"></div>
        <nav class="fr-nav" id="fr-navigation" role="navigation" aria-label="Menu principal">
        </nav>
      </div>
    </div>
{% endblock %}

core/templates/core/blocks/list_subdivisions.html
{% for place in list %}

<li>
    {% if subdivisions_link %}
    <strong>{{ place.name }}{%if place.insee %} ({{place.insee}}){% endif %} :</strong>  
        <a href="{% url entry_link.view place.slug %}">{{ entry_link.title }}</a> / 
        <a href="{% url subdivisions_link.view place.slug %}">{{ subdivisions_link.title }}</a>
    {% else %}
    <a href="{% url entry_link.view place.slug %}">
        <strong>{{ place.name }}{%if place.insee %} ({{place.insee}}){% endif %}</strong>
    </a>
    {% endif %}
</li>
{% endfor %}

core/templates/core/blocks/publications_list.html
{% load dsfr_tags %}
<div id="oc-publications-list" class="fr-grid-row  fr-grid-row--gutters">
        {% for card in data %}
        <div class="fr-col-12 {% if width_class %}{{ width_class }}{% else %}fr-col-md-3{% endif %}">
            {% dsfr_card card extra_classes="fr-card--no-arrow" new_tab=True %}
        </div>
        {% endfor %}
</div><!-- end publications list -->

core/templates/core/blocks/publications_tags_list.html
{% load dsfr_tags %}
{% if filters.filter_tags %}
    <ul class="fr-tags-group">
    {% for filter_tag in filters.filter_tags %}
        {% dsfr_tag filter_tag extra_classes="fr-fi-close-line fr-tag--icon-right" %}
    {% endfor %}
    </ul>
{% endif %}

core/templates/core/blocks/sitemap_region_entry.html
<h3>{{ region.name }}</h3>
<ul>
    {% if region.counts.departements > 1 %}
    <li><a href="{% url 'core:page_region_liste_departements' region.slug %}">
        Voir les {{ region.counts.departements }} départements de la Région {{ region.name }}
    </a></li>
    {% endif %}

    {% if region.name != 'Mayotte' %}
    {# Mayotte is not a region per se #}
    <li><a href="{% url 'core:page_region_liste_communes' region.slug %}">
        Voir les {{ region.counts.communes }} communes de la Région {{ region.name }}
    </a></li>
    {% else %}
    <li><a href="{% url 'core:page_departement_liste_communes' region.slug %}">
        Voir les {{ region.counts.communes }} communes de Mayotte
    </a></li>
    {% endif %}
</ul>

core/templates/core/blocks/source_aspic_banatic.html
<p class="fr-text--xs">
    Source des données : <a
        href="https://www.data.gouv.fr/fr/datasets/les-donnees-contextuelles-des-intercommunalites-et-autres-structures-territoriales/"
        target="_blank" rel="noopener">
            Aspic/Banatic
                <span> (fichier {{ file }})</span>.
        </a> Année : {{ max_year }}, sauf précision.
</p>

core/templates/core/blocks/sources_line.html
<p class="fr-text--xs">
    Source(s) des données :
    {% for source in sources %}
        {% if source.url %}
        <a
            href="{{ source.url }}"
            target="_blank" rel="noopener">
                {% if source.public_label %}
                    {{ source.public_label }}
                {% else %}
                    {{ source.title }}
                {% endif %}
            </a>
        {% else%}
            {% if source.public_label %}
                {{ source.public_label }}
            {% else %}
                {{ source.title }}
            {% endif %}
        {% endif %}
        (année : {{ source.year }}, sauf précision)
        {% if not forloop.last %} – {% endif %}
    {% endfor %} 
</p>