config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from config.api import api

# Personalize the Django admin header
admin.site.site_header = "Administration d’Open Collectivités"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    url(r"^favicon\.ico$", RedirectView.as_view(url="/static/favicon.ico")),
    path("api/", api.urls),
    path("cms/", include(wagtailadmin_urls)),
    path("wd_documents/", include(wagtaildocs_urls)),
    path("", include("core.urls")),
    path("", include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.error404"
handler500 = "core.views.error500"

core/urls.py
from django.urls import path, re_path
from . import views

app_name = "core"
urlpatterns = [
    path(
        "commune/<slug:slug>/",
        views.page_commune_detail,
        name="page_commune_detail",
    ),
    path(
        "epci/<slug:slug>/",
        views.page_epci_detail,
        name="page_epci_detail",
    ),
    path(
        "departement/<slug:slug>/",
        views.page_departement_detail,
        name="page_departement_detail",
    ),
    path(
        "departement/<slug:slug>/liste-communes/",
        views.page_departement_liste_communes,
        name="page_departement_liste_communes",
    ),
    path(
        "departement/<slug:slug>/liste-epcis/",
        views.page_departement_liste_epcis,
        name="page_departement_liste_epcis",
    ),
    path(
        "region/<slug:slug>/",
        views.page_region_detail,
        name="page_region_detail",
    ),
    path(
        "region/<slug:slug>/liste-communes/",
        views.page_region_liste_communes,
        name="page_region_liste_communes",
    ),
    path(
        "region/<slug:slug>/liste-epcis/",
        views.page_region_liste_epcis,
        name="page_region_liste_epcis",
    ),
    path(
        "region/<slug:slug>/liste-departements/",
        views.page_region_liste_departements,
        name="page_region_liste_departements",
    ),
    re_path(
        r"^compare\/commune\/(?P<slug1>[-\w]+)\/(?P<slug2>[-\w]+)\/?(?P<slug3>[-\w]+)?\/?(?P<slug4>[-\w]+)?\/?",
        views.page_commune_compare,
        name="page_commune_compare",
    ),
    path(
        "export/commune/<slug:slug>",
        views.csv_commune_export,
        name="csv_commune_export",
    ),
    re_path(
        r"^compare_export\/commune\/(?P<slug1>[-\w]+)\/(?P<slug2>[-\w]+)\/?(?P<slug3>[-\w]+)?\/?(?P<slug4>[-\w]+)?\/?",
        views.csv_compare_communes_from_list,
        name="csv_compare_communes_from_list",
    ),
    path(
        "compare_export/departement/membres/<slug:slug>",
        views.csv_departement_compare_communes,
        name="csv_departement_compare_communes",
    ),
    path(
        "compare_export/epci/membres/<slug:slug>",
        views.csv_epci_compare_communes,
        name="csv_epci_compare_communes",
    ),
    re_path(
        r"^compare\/.*",
        views.page_not_yet,
        name="page_place_compare",
    ),
    path("publications/", views.page_publications, name="page_publications"),
    path("tests/", views.page_tests, name="page_tests"),
    path("plan/", views.page_sitemap, name="page_sitemap"),
    path("test_404/", views.error404, {"exception": Exception()}, name="page_test_404"),
    path("test_500/", views.error500, {"exception": Exception()}, name="page_test_500"),
    path("test_50x/", views.error50x, {"exception": Exception()}, name="page_test_50x"),
]

opencollectivites/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r"^favicon\.ico$", RedirectView.as_view(url="/static/favicon.ico")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/france/", include("francesubdivisions.urls")),
    path("api/aspic/", include("aspic.urls")),
    path("", include("core.urls")),
]

core/views/base.py
from django.shortcuts import render
from django.views.decorators.http import require_safe
from core.models import Scope, Source, Topic
from core.services.utils import init_payload
from francedata.models import Region


@require_safe
def error404(request, exception):
    payload = init_payload("Erreur")
    payload["exception"] = exception
    return render(request, "core/404.html", payload, status=404)


@require_safe
def error500(request, *args, **argv):
    payload = init_payload("Erreur serveur")
    return render(request, "core/500.html", payload, status=500)


@require_safe
def error50x(request, *args, **argv):
    payload = init_payload("Erreur serveur")
    return render(request, "core/50x.html", payload, status=503)


@require_safe
def page_not_yet(request, **kwargs):
    payload = init_payload("Page en construction")
    return render(request, "core/page_not_yet.html", payload)


@require_safe
def page_sitemap(request):
    payload = init_payload("Plan du site")

    regions = Region.objects.order_by("name")
    regions_data = []
    for r in regions:
        regions_data.append(
            {"name": r.name, "slug": r.slug, "counts": r.subdivisions_count()}
        )

    filter_data = {}
    filter_data["topic"] = Topic.objects.order_by("name")
    filter_data["scope"] = Scope.objects.order_by("name")
    filter_data["source"] = Source.objects.order_by("title")
    payload["filter_data"] = filter_data

    payload["regions_data"] = regions_data

    return render(request, "core/sitemap.html", payload)


@require_safe
def page_tests(request):
    payload = init_payload("Tests")
    payload["breadcrumb_with_link"] = {
        "links": [{"url": "test-url", "title": "Test title"}],
        "current": "Test page",
    }
    payload["context"]["hide_brand"] = False
    return render(request, "core/tests.html", payload)

core/views/communes.py
from collectivity_pages.services.utils import get_messages_for_collectivity
from core.services.publications import list_publications_for_collectivity
from django.urls.base import reverse
from core.services.utils import init_payload
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_safe
from francedata.models import Commune

from collectivity_pages.services.communes import commune_data, communes_compare

from dsfr.utils import generate_summary_items


@require_safe
def page_commune_detail(request, slug):
    commune = get_object_or_404(Commune, slug=slug)

    payload = init_payload(f"Données locales commune : {commune.name}")
    payload["slug"] = slug
    payload["siren"] = commune.siren
    payload["commune_name"] = commune.name
    payload["data"] = commune_data(commune)
    payload["page_data"] = {"type": "commune", "slug": slug}
    payload["data"]["tables_header"] = ["Intitulé", "Donnée"]
    payload["data"]["table_header_zonage"] = ["Intitulé", "Statut"]
    payload["data"]["table_header_interco"] = ["Type", "Nom", "Sigle type"]

    payload["page_menu"] = {
        "title": "Sommaire",
        "items": generate_summary_items(
            [
                "Données de contexte",
                "Intercommunalités et zonage",
                "Ressources financières et fiscales",
                "Comparaison avec d’autres communes",
                "Études, statistiques et outils",
            ]
        ),
        "extra_classes": "fr-sidemenu--sticky-full-height fr-sidemenu--right",
    }

    payload["messages"] = get_messages_for_collectivity(
        collectivity_type="COMM", collectivity_slug=slug
    )

    payload["publications"] = list_publications_for_collectivity(
        collectivity_type="commune", collectivity_slug=commune.slug
    )

    payload["context"]["hide_brand"] = False
    return render(request, "core/commune_detail.html", payload)


@require_safe
def page_commune_compare(request, slug1, slug2, slug3=0, slug4=0):
    slugs = [slug1, slug2]
    communes = []
    slugs_dict = {"slug1": slug1, "slug2": slug2}

    """
    Storing all supplementary slugs in slug2 because the reverse() function is not able to 
    figure out the optional slashes.
    """
    if slug3:
        slugs.append(slug3)
        slugs_dict["slug2"] = f"{slugs_dict['slug2']}/{slug3}"
    if slug4:
        slugs.append(slug4)
        slugs_dict["slug2"] = f"{slugs_dict['slug2']}/{slug4}"

    for s in slugs:
        commune = get_object_or_404(Commune, slug=s)
        communes.append(commune)

    payload = init_payload("Comparaison de communes")
    payload["data"] = {}
    payload["data"]["tables"] = communes_compare(communes)
    payload["data"]["tables_header"] = ["Intitulé"] + payload["data"]["tables"][
        "places_names"
    ]

    payload["data"]["export_link"] = reverse(
        "core:csv_compare_communes_from_list", kwargs=slugs_dict
    )

    return render(request, "core/commune_compare.html", payload)

core/views/csv_exports.py
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_safe

from collectivity_pages.services.communes import (
    compare_communes_for_export,
)

from francedata.models import Departement, Commune, Epci


###############
# CSV exports #
###############
@require_safe
def csv_commune_export(request, slug):
    commune = Commune.objects.filter(slug=slug)
    # Commune.objects.filter is used instead of get_object_or_404 because
    # compare_communes_for_export expects a QuerySet
    filename = f"export-commune-{slug}"
    response = compare_communes_for_export(commune, filename)
    return response


@require_safe
def csv_compare_communes_from_list(request, slug1, slug2, slug3=0, slug4=0):
    slugs = [slug1, slug2]
    if slug3:
        slugs.append(slug3)
    if slug4:
        slugs.append(slug4)

    communes = Commune.objects.filter(slug__in=slugs)
    filename = f"comparaisons-communes-{'-'.join(slugs)}"

    response = compare_communes_for_export(communes, filename)
    return response


@require_safe
def csv_epci_compare_communes(request, slug):
    epci = get_object_or_404(Epci, slug=slug)
    filename = f"comparaisons-communes-{slug}"
    response = compare_communes_for_export(epci.commune_set.all(), filename)
    return response


@require_safe
def csv_departement_compare_communes(request, slug):
    departement = get_object_or_404(Departement, slug=slug)
    filename = f"comparaisons-communes-{slug}"
    response = compare_communes_for_export(departement.commune_set.all(), filename)
    return response

core/views/departements.py
from collectivity_pages.services.departements import departement_data
from collectivity_pages.services.utils import get_messages_for_collectivity
from core.services.publications import list_publications_for_collectivity
from core.services.utils import init_payload
from django.urls.base import reverse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_safe
from dsfr.utils import generate_summary_items
from francedata.models import Departement


@require_safe
def page_departement_detail(request, slug):
    departement = get_object_or_404(Departement, slug=slug)

    payload = init_payload(f"Données locales département : {departement.name}")
    payload["slug"] = slug
    payload["siren"] = departement.siren
    payload["data"] = departement_data(departement)
    payload["data"]["tables_header"] = ["Intitulé", "Donnée"]
    payload["page_menu"] = {
        "title": "Sommaire",
        "items": generate_summary_items(
            [
                "Données de contexte",
                "Ressources financières et fiscales",
                "Périmètre",
                "Études, statistiques et outils"
            ]
        ),
        "extra_classes": "fr-sidemenu--sticky-full-height fr-sidemenu--right",
    }

    payload["messages"] = get_messages_for_collectivity(
        collectivity_type="DEPT", collectivity_slug=slug
    )

    payload["publications"] = list_publications_for_collectivity(
        collectivity_type="departement", collectivity_slug=departement.slug
    )

    return render(request, "core/departement_detail.html", payload)


@require_safe
def page_departement_liste_communes(request, slug):
    departement = get_object_or_404(Departement, slug=slug)
    max_year = max(departement.commune_set.values_list("years", flat=True))
    communes = departement.commune_set.filter(years=max_year).order_by("name")
    payload = init_payload(
        f"Liste des { communes.count() } communes du département {departement.name}",
        links=[
            {
                "title": f"Fiche département : {departement.name}",
                "url": reverse(
                    "core:page_departement_detail", kwargs={"slug": departement.slug}
                ),
            }
        ],
    )
    payload["list"] = communes
    payload["entry_link"] = {
        "title": "Fiche commune",
        "view": "core:page_commune_detail",
    }
    return render(request, "core/place_list_direct_subdivisions.html", payload)


@require_safe
def page_departement_liste_epcis(request, slug):
    departement = get_object_or_404(Departement, slug=slug)
    max_year = max(departement.list_epcis().values_list("years", flat=True))
    epcis = departement.list_epcis().filter(years=max_year).order_by("slug")

    payload = init_payload(
        f"Liste des { len(epcis) } EPCI du département {departement.name}",
        links=[
            {
                "title": f"Fiche département : {departement.name}",
                "url": reverse(
                    "core:page_departement_detail", kwargs={"slug": departement.slug}
                ),
            }
        ],
    )
    payload["list"] = epcis
    payload["entry_link"] = {
        "title": "Fiche EPCI",
        "view": "core:page_epci_detail",
    }
    return render(request, "core/place_list_direct_subdivisions.html", payload)

core/views/epcis.py
from collectivity_pages.services.utils import get_messages_for_collectivity
from core.services.utils import init_payload
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_safe
from dsfr.utils import generate_summary_items
from francedata.models import Epci

from collectivity_pages.services.epcis import epci_data

from core.services.publications import (
    list_documents,
    documents_to_cards,
    list_publications_for_collectivity,
)


@require_safe
def page_epci_detail(request, slug):
    epci = get_object_or_404(Epci, slug=slug)

    payload = init_payload(f"Données locales intercommunalité : {epci.name}")
    payload["slug"] = slug
    payload["siren"] = epci.siren
    payload["epci_name"] = epci.name
    payload["data"] = epci_data(epci.siren)
    payload["data"]["tables_header"] = ["Intitulé", "Donnée"]

    payload["page_menu"] = {
        "title": "Sommaire",
        "items": generate_summary_items(
            [
                "Données socio-économiques",
                "Coordonnées du siège",
                "Périmètre & compétences",
                "Ressources financières et fiscales",
                "Études, statistiques et outils",
            ]
        ),
        "extra_classes": "fr-sidemenu--sticky-full-height fr-sidemenu--right",
    }

    tools, total_count = list_documents(document_type=3, publication_page=4, limit=10)
    payload["tools_list"] = documents_to_cards(tools)

    payload["messages"] = get_messages_for_collectivity(
        collectivity_type="EPCI", collectivity_slug=epci.slug
    )

    payload["publications"] = list_publications_for_collectivity(
        collectivity_type="epci", collectivity_slug=epci.slug
    )

    return render(request, "core/epci_detail.html", payload)

core/views/publications.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.conf import settings
from django.views.decorators.http import require_GET, require_safe

from core.services.utils import init_payload
from core.services.publications import (
    list_documents,
    documents_to_cards,
    publication_filters,
)


@require_safe
def page_publications(request):
    payload = init_payload("Études, statistiques et outils locaux")

    documents, total_count = list_documents(
        topic=request.GET.get("topic"),
        scope=request.GET.get("scope"),
        document_type=request.GET.get("document_type"),
        publication_page=request.GET.get("publication_page"),
        source_org=request.GET.get("source_org"),
        year=request.GET.get("year"),
        commune=request.GET.get("commune"),
        epci=request.GET.get("epci"),
        departement=request.GET.get("departement"),
        region=request.GET.get("region"),
        before=request.GET.get("before"),
        after=request.GET.get("after"),
    )

    cards = documents_to_cards(documents)

    paginated_docs = Paginator(cards, settings.PUBLICATIONS_PER_PAGE)

    data = {}
    data["total"] = paginated_docs.count
    data["cards_page"] = paginated_docs.get_page(request.GET.get("page"))

    payload["data"] = data

    payload["filters"] = publication_filters(request)

    return render(request, "core/publications.html", payload)

core/templates/core/50x.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div class="fr-container fr-mt-4w fr-mb-6w">
  <div class="fr-grid-row fr-grid-row--gutters ">
    <div class="fr-col-12 fr-col-md-6">
      <h1>Le site est actuellement inaccessible</h1>
      <p>Nous mettons tout en oeuvre pour que le site soit de nouveau accessible rapidement. Veuillez revenir plus tard.</p>
    </div>
    <div class="fr-col-12 fr-col-md-6">
        <img
        src="{% static 'img/undraw_server_down_s4lk.svg' %}"
        style="width:100%"
        alt=""
      />
    </div>
  </div>
</div>
{% endblock %}

core/templates/core/base.html
{% load static wagtailuserbar matomo dsfr_tags %}
<!doctype html>
<html lang="fr" data-fr-scheme="system" {% if SITE_CONFIG.mourning %}data-fr-mourning{% endif %}>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  {% dsfr_css %}
  {% dsfr_favicon %}

  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/remixicon/remixicon.css' %}">
  {% block extra_css %}{% endblock %}

  {% block  title %}
  <title>{% if self.seo_title %}
      {{ self.seo_title }}
    {% elif self.title %}
      {{ self.title }}  — Open Collectivités
    {% elif title %}
      {{ title }} — Open Collectivités
    {% else %}
      Open Collectivités
    {% endif %}</title>
  {% endblock title %}

  {% block description %}
    {% if self.search_description %}<meta name="description" content ="{{ self.search_description }}" />{% endif %}
  {% endblock description %}
</head>

<body class="{% block body_class %}{% endblock %}">
    {% block skiplinks %}
        {% dsfr_skiplinks skiplinks %}
    {% endblock %}
    {% block custom_header %}
      {% include "core/blocks/header.html" with hide_brand=context.hide_brand %}
    {% endblock %}
    {% dsfr_theme_modale %}
    {% wagtailuserbar %}

    <main id="content">
      {% block content %}{% endblock %}
    </main>

    {% include "core/blocks/footer_categories.html" %}
    {% include "core/blocks/footer.html" %}

  {% dsfr_js %}
  {% block extra_js %}{% endblock %}
  {% if debug is not True %}{% matomo %}{% endif %}
</body>

</html>

core/templates/core/epci_detail.html
{% extends "core/base.html" %}
{% load static dsfr_tags %}

{% block extra_css %}
{% endblock %}

{% block content %}
<div class="fr-container fr-mt-4w fr-mb-6w">
    {% dsfr_breadcrumb breadcrumb_data %}

  {# Intro #}
  <h1>{{ title }}</h1>

  {% for message in messages %}
    {% dsfr_callout text=message.message %}
  {% endfor %}

  <p>
  Code SIREN : <a href="https://annuaire-entreprises.data.gouv.fr/entreprise/{{ siren }}" target="_blank" rel="noopener noreferrer">{{ siren }}</a>
  </p>

  {# Special case for the Métropole de Lyon #}
  {% if slug == "metropole-de-lyon-200046977" %}
    <p>
      La Métropole de Lyon est une métropole française située dans la région <a href="{% url 'core:page_region_detail' 'auvergne-rhone-alpes' %}">Auvergne-Rhône-Alpes</a>.  
    </p>
  {% else %}
    <p>
      {{ data.name }} est une {{ data.type.name}} ({{data.type.acronym}}) française{% if data.seat %} dont le siège est
      <a href="{% url 'core:page_commune_detail' data.seat.slug %}">{{ data.seat.name }}{% endif %}</a>.  
    </p>

    <p>
    {% if data.departements.count == 1 %}
      Elle est située intégralement dans le département
      {% with data.departements|first as departement %}
        <a href="{% url 'core:page_departement_detail' departement.departement__slug %}">{{ departement.departement__name }}</a>{% if departement.departement__region__name %}
        et la région <a href="{% url 'core:page_region_detail' departement.departement__region__slug %}">{{ departement.departement__region__name }}</a>{% endif %}.
      {% endwith %}
    {% else %}
      Elle est située sur les départements 
        {% for departement in data.departements %}
          <a href="{% url 'core:page_departement_detail' departement.departement__slug %}">{{ departement.departement__name }}</a>{% if forloop.last %} {% else %}, {% endif%}
        {%endfor%}
        {% if data.regions.count == 1 %}
          et la région <a href="{% url 'core:page_region_detail' data.region.slug %}">{{ data.region.name }}</a>.
        {% elif data.regions.count > 1 %}
          et les régions
          {% for region in data.regions %}
            <a href="{% url 'core:page_region_detail' region.departement__region__slug %}">{{ region.departement__region__name }}</a>{% if forloop.last %}.{% else %}, {% endif%}
          {%endfor%}
        {% else %}
        .
        {% endif %}
    {% endif %}
    </p>
  {% endif %}

  <p>
    {% if data.president.last_name %}Le président actuel est
    {{ data.president.civility | safe }} {{ data.president.first_name }} {{ data.president.last_name }}.{% endif%}
  </p>

  {# Navigation #}
  <div id="navigation-tiles" class="fr-grid-row fr-grid-row--gutters">
    <div class="fr-col-12 fr-col-md-2">
      {% dsfr_tile data.communes_list %}
    </div>

    {% if data.seat %}
      <div class="fr-col-12 fr-col-md-2">
        {% dsfr_tile data.seat %}
      </div>
    {% endif %}

    {% if data.departement %}
      <div class="fr-col-12 fr-col-md-2">
        {% dsfr_tile data.departement %}
      </div>
    {% endif %}

    {% if data.region %}
    <div class="fr-col-12 fr-col-md-2">
      {% dsfr_tile data.region %}
    </div>
    {% endif %}
  </div>

  {# Tables #}
  <div class="fr-grid-row fr-grid-row--gutters fr-mt-4w fr-mb-6w" id="oc-collectivity-main">
    <aside id="vue-sidemenu" class="fr-col-12 fr-col-md-4">
      {% dsfr_sidemenu page_menu %}
    </aside>
    <article class="fr-col-12 fr-col-md-8">
      <h2 id="donnees-socio-economiques">Données socio-économiques</h2>
      {% dsfr_table caption="Population" content=data.tables.epci_population.rows header=data.tables_header extra_classes="oc-table--fullwidth oc-table--force10" %}
      {% include "core/blocks/sources_line.html" with sources=data.tables.epci_population.sources %}

      <a
        title="Comparateur de territoires INSEE"
        href="https://www.insee.fr/fr/statistiques/1405599?geo=EPCI-{{ siren }}"
        target="_blank"
        rel="noopener"
        class="fr-link fr-link--lg fr-fi-external-link-line fr-link--icon-right"
      >
        Plus d’informations sur le comparateur de territoires INSEE
      </a>

      <h2 id="coordonnees-du-siege">Coordonnées du siège</h2>
      {% if data.contact %}
      <dl>
        <dt>Adresse postale :</dt>
        <dd>{% if data.contact.address1|length > 0 %}{{ data.contact.address1 }} <br />{% endif %}
        {% if data.contact.address2|length > 0 %}{{ data.contact.address2 }} <br />{% endif %}
        {% if data.contact.address3|length > 0 %}{{ data.contact.address3 }} <br />{% endif %}
        {{ data.contact.postcode }} {{ data.contact.city|upper }}</dd>

        {% if data.contact.website|length > 0 %}
          <dt>Site internet :</dt>
          <dd><a href="{{ data.contact.website }}" target="_blank" rel="noopener">{{ data.contact.website }}</a></dd>
        {% endif %}

        {% if data.contact.telephone|length > 0 %}
          <dt>Téléphone :</dt>
          <dd><a href="tel:+33{{ data.contact.telephone|slice:'1:' }}">{{ data.contact.telephone }}</a></dd>
        {% endif %}
        {% if data.contact.fax|length > 0 %}
        <dt>Fax :</dt>
        <dd><a href="fax:+33{{ data.contact.fax|slice:'1:' }}">{{ data.contact.fax }}</a></dd>
        {% endif %}

        {% if data.contact.email|length > 0 %}<dt>Courriel :</dt>
        <dd><a href="mailto:{{ data.contact.email }}">{{ data.contact.email }}</a></dd>{% endif %}
      </dl>
      {% endif %}

      <h2 id="perimetre-competences">Périmètre & compétences</h2>
      <h3 id="perimetre">Périmètre</h3>
      <p>
        Nombre total de communes membres : {{ data.members.count }}<br />
      
        {% for member in data.members %}
          <a href="{% url 'core:page_commune_detail' member.slug %}">{{ member.name }}</a>{% if forloop.last %}.{% else %}, {% endif%}
        {%endfor%}
      </p>

      <a
        title="Comparatif des communes membres"
        href="{% url 'core:csv_epci_compare_communes' slug %}"
        target="_blank"
        rel="noopener"
        class="fr-link fr-link--lg fr-fi-download-line fr-link--icon-right"
      >
        Télécharger le comparatif des {{ data.members.count }} communes au format csv
      </a>

      <h3>Compétences</h3>
      <p>Nombre total de compétences exercées : {{ data.competences.count }} </p>

      <a
        title="Fiche EPCI sur Banatic"
        href="https://www.banatic.interieur.gouv.fr/V5/recherche-de-groupements/fiche-raison-sociale.php?siren={{ siren }}"
        target="_blank"
        rel="noopener"
        class="fr-link fr-link--lg fr-fi-external-link-line fr-link--icon-right"
      >
        Voir le détail sur la fiche EPCI de la base nationale sur l’intercommunalité
      </a>

      <h2 id="ressources-financieres-et-fiscales">
        Ressources financières et fiscales
      </h2>
      {% dsfr_table caption="Dotation globale de fonctionnement" content=data.tables.epci_dgf.rows extra_classes="oc-table--fullwidth oc-table--force10" %}
      {% include "core/blocks/sources_line.html" with sources=data.tables.epci_dgf.sources %}


      {% dsfr_table caption="Fonds national de péréquation des ressources intercommunales et communales (FPIC)" content=data.tables.epci_fpic.rows extra_classes="oc-table--fullwidth oc-table--force10" %}
      {% include "core/blocks/sources_line.html" with sources=data.tables.epci_fpic.sources %}

      {# Publications lists #}
      {% include "core/blocks/collectivity_publications.html" with publications=publications %}
    </article> <!-- end left column -->
  </div> <!-- end columns container-->
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'lib/vue-2.6.12/vue.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/sidemenu-autoscroll.js' %}"></script>
{% endblock %}

core/templates/core/page_not_yet.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div class="fr-container fr-mt-4w fr-mb-6w">
  <div class="fr-grid-row fr-grid-row--gutters ">
    <div class="fr-col-12 fr-col-md-6">
      <h1>Page en construction</h1>
      <p>
        <a href="/" class="fr-link fr-link--lg fr-fi-arrow-right-line fr-link--icon-right" target="_self"
          >Retour à la page d’accueil</a
        >
      </p>
    </div>
    <div class="fr-col-12 fr-col-md-6">
        <img
        src="{% static 'img/undraw_work_in_progress_uhmv.svg' %}"
        style="width:100%"
        alt=""
      />
    </div>
  </div>
</div>
{% endblock %}